const EMAIL_CHECK = "^\S+@\S+\.\S+$";
const OPEN_DESKTOP = 3;
const OPEN_TABLET = 2;
const OPEN_MOBILE = 1;
const SHORT_FILM_DURATION = 40;
const USERNAME_CHECK = "[а-яА-Яa-zA-ZёË\- ]{1,}";

export {
  EMAIL_CHECK,
  OPEN_DESKTOP,
  OPEN_TABLET,
  OPEN_MOBILE,
  SHORT_FILM_DURATION,
  USERNAME_CHECK,
};
